#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit(1);
}

require __DIR__ . '/vendor/autoload.php';

use Zakirkun\Jett\Console\Application;

$app = new Application();
exit($app->run($argv));
